package com.guokrspace;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.guokrspace.PersonalInformation;
import com.guokrspace.OrderRecord;
import com.guokrspace.SearchHistory;

import com.guokrspace.PersonalInformationDao;
import com.guokrspace.OrderRecordDao;
import com.guokrspace.SearchHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personalInformationDaoConfig;
    private final DaoConfig orderRecordDaoConfig;
    private final DaoConfig searchHistoryDaoConfig;

    private final PersonalInformationDao personalInformationDao;
    private final OrderRecordDao orderRecordDao;
    private final SearchHistoryDao searchHistoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personalInformationDaoConfig = daoConfigMap.get(PersonalInformationDao.class).clone();
        personalInformationDaoConfig.initIdentityScope(type);

        orderRecordDaoConfig = daoConfigMap.get(OrderRecordDao.class).clone();
        orderRecordDaoConfig.initIdentityScope(type);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        personalInformationDao = new PersonalInformationDao(personalInformationDaoConfig, this);
        orderRecordDao = new OrderRecordDao(orderRecordDaoConfig, this);
        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);

        registerDao(PersonalInformation.class, personalInformationDao);
        registerDao(OrderRecord.class, orderRecordDao);
        registerDao(SearchHistory.class, searchHistoryDao);
    }
    
    public void clear() {
        personalInformationDaoConfig.getIdentityScope().clear();
        orderRecordDaoConfig.getIdentityScope().clear();
        searchHistoryDaoConfig.getIdentityScope().clear();
    }

    public PersonalInformationDao getPersonalInformationDao() {
        return personalInformationDao;
    }

    public OrderRecordDao getOrderRecordDao() {
        return orderRecordDao;
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

}
