package com.guokrspace;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.guokrspace.OrderRecord;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ORDER_RECORD.
*/
public class OrderRecordDao extends AbstractDao<OrderRecord, Long> {

    public static final String TABLENAME = "ORDER_RECORD";

    /**
     * Properties of entity OrderRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property StartAddr = new Property(1, String.class, "startAddr", false, "START_ADDR");
        public final static Property DestAddr = new Property(2, String.class, "destAddr", false, "DEST_ADDR");
        public final static Property StartLat = new Property(3, String.class, "startLat", false, "START_LAT");
        public final static Property StartLng = new Property(4, String.class, "startLng", false, "START_LNG");
        public final static Property DestLat = new Property(5, String.class, "destLat", false, "DEST_LAT");
        public final static Property DestLng = new Property(6, String.class, "destLng", false, "DEST_LNG");
        public final static Property Mileage = new Property(7, String.class, "mileage", false, "MILEAGE");
        public final static Property Price = new Property(8, String.class, "price", false, "PRICE");
        public final static Property CarType = new Property(9, String.class, "carType", false, "CAR_TYPE");
        public final static Property OrderTime = new Property(10, String.class, "orderTime", false, "ORDER_TIME");
    };


    public OrderRecordDao(DaoConfig config) {
        super(config);
    }
    
    public OrderRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ORDER_RECORD' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'START_ADDR' TEXT," + // 1: startAddr
                "'DEST_ADDR' TEXT," + // 2: destAddr
                "'START_LAT' TEXT," + // 3: startLat
                "'START_LNG' TEXT," + // 4: startLng
                "'DEST_LAT' TEXT," + // 5: destLat
                "'DEST_LNG' TEXT," + // 6: destLng
                "'MILEAGE' TEXT," + // 7: mileage
                "'PRICE' TEXT," + // 8: price
                "'CAR_TYPE' TEXT," + // 9: carType
                "'ORDER_TIME' TEXT);"); // 10: orderTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ORDER_RECORD'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, OrderRecord entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String startAddr = entity.getStartAddr();
        if (startAddr != null) {
            stmt.bindString(2, startAddr);
        }
 
        String destAddr = entity.getDestAddr();
        if (destAddr != null) {
            stmt.bindString(3, destAddr);
        }
 
        String startLat = entity.getStartLat();
        if (startLat != null) {
            stmt.bindString(4, startLat);
        }
 
        String startLng = entity.getStartLng();
        if (startLng != null) {
            stmt.bindString(5, startLng);
        }
 
        String destLat = entity.getDestLat();
        if (destLat != null) {
            stmt.bindString(6, destLat);
        }
 
        String destLng = entity.getDestLng();
        if (destLng != null) {
            stmt.bindString(7, destLng);
        }
 
        String mileage = entity.getMileage();
        if (mileage != null) {
            stmt.bindString(8, mileage);
        }
 
        String price = entity.getPrice();
        if (price != null) {
            stmt.bindString(9, price);
        }
 
        String carType = entity.getCarType();
        if (carType != null) {
            stmt.bindString(10, carType);
        }
 
        String orderTime = entity.getOrderTime();
        if (orderTime != null) {
            stmt.bindString(11, orderTime);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public OrderRecord readEntity(Cursor cursor, int offset) {
        OrderRecord entity = new OrderRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // startAddr
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // destAddr
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // startLat
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // startLng
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // destLat
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // destLng
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // mileage
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // price
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // carType
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // orderTime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, OrderRecord entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStartAddr(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDestAddr(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setStartLat(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStartLng(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDestLat(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDestLng(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setMileage(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPrice(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setCarType(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setOrderTime(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(OrderRecord entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(OrderRecord entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
