package com.guokrspace.duducar.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personalInformationDaoConfig;
    private final DaoConfig orderRecordDaoConfig;

    private final PersonalInformationDao personalInformationDao;
    private final OrderRecordDao orderRecordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personalInformationDaoConfig = daoConfigMap.get(PersonalInformationDao.class).clone();
        personalInformationDaoConfig.initIdentityScope(type);

        orderRecordDaoConfig = daoConfigMap.get(OrderRecordDao.class).clone();
        orderRecordDaoConfig.initIdentityScope(type);

        personalInformationDao = new PersonalInformationDao(personalInformationDaoConfig, this);
        orderRecordDao = new OrderRecordDao(orderRecordDaoConfig, this);

        registerDao(PersonalInformation.class, personalInformationDao);
        registerDao(OrderRecord.class, orderRecordDao);
    }
    
    public void clear() {
        personalInformationDaoConfig.getIdentityScope().clear();
        orderRecordDaoConfig.getIdentityScope().clear();
    }

    public PersonalInformationDao getPersonalInformationDao() {
        return personalInformationDao;
    }

    public OrderRecordDao getOrderRecordDao() {
        return orderRecordDao;
    }

}
