package com.guokrspace.duducar.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DRIVER_RECORD.
 */
public class DriverRecord {

    private Long id;
    private String name;
    private String mobile;
    private String avatar;
    private String plate;
    private String picture;
    private String description;

    public DriverRecord() {
    }

    public DriverRecord(Long id) {
        this.id = id;
    }

    public DriverRecord(Long id, String name, String mobile, String avatar, String plate, String picture, String description) {
        this.id = id;
        this.name = name;
        this.mobile = mobile;
        this.avatar = avatar;
        this.plate = plate;
        this.picture = picture;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getPlate() {
        return plate;
    }

    public void setPlate(String plate) {
        this.plate = plate;
    }

    public String getPicture() {
        return picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
