package com.guokrspace.duducar.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MESSAGE_INFO.
 */
public class MessageInfo {

    private Integer id;
    private String title;
    private String date;
    private String imgurl;
    private String content;
    private String url;

    public MessageInfo() {
    }

    public MessageInfo(Integer id, String title, String date, String imgurl, String content, String url) {
        this.id = id;
        this.title = title;
        this.date = date;
        this.imgurl = imgurl;
        this.content = content;
        this.url = url;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getImgurl() {
        return imgurl;
    }

    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
