package com.guokrspace.duducar.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SEARCH_HISTORY.
 */
public class SearchHistory {

    private Long id;
    private String address;
    private String details;

    public SearchHistory() {
    }

    public SearchHistory(Long id) {
        this.id = id;
    }

    public SearchHistory(Long id, String address, String details) {
        this.id = id;
        this.address = address;
        this.details = details;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getDetails() {
        return details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

}
