# Uncomment this line to define a global platform for your project
platform :ios, '7.1'
# Uncomment this line if you're using Swift
use_frameworks!

target 'duducar' do
pod 'CocoaAsyncSocket'
pod 'CocoaLumberjack'
pod 'BaiduMapKit'
pod 'FMDB'
pod 'Masonry'
end

target 'duducarTests' do

end

target 'duducarUITests' do

end

