# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'duducar' do
pod 'CocoaAsyncSocket'
pod 'CocoaLumberjack'
pod 'FMDB'
pod 'Masonry'
pod 'BaiduMapKit'
pod 'HCSStarRatingView', '~> 1.4.3'
pod 'SDWebImage', '~>3.7'
end

target 'duducarTests' do

end

target 'duducarUITests' do

end

