package com.guokrspace.dududriver.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.guokrspace.dududriver.database.PersonalInformation;
import com.guokrspace.dududriver.database.OrderRecord;
import com.guokrspace.dududriver.database.BaseNotice;
import com.guokrspace.dududriver.database.BillRecord;

import com.guokrspace.dududriver.database.PersonalInformationDao;
import com.guokrspace.dududriver.database.OrderRecordDao;
import com.guokrspace.dududriver.database.BaseNoticeDao;
import com.guokrspace.dududriver.database.BillRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personalInformationDaoConfig;
    private final DaoConfig orderRecordDaoConfig;
    private final DaoConfig baseNoticeDaoConfig;
    private final DaoConfig billRecordDaoConfig;

    private final PersonalInformationDao personalInformationDao;
    private final OrderRecordDao orderRecordDao;
    private final BaseNoticeDao baseNoticeDao;
    private final BillRecordDao billRecordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personalInformationDaoConfig = daoConfigMap.get(PersonalInformationDao.class).clone();
        personalInformationDaoConfig.initIdentityScope(type);

        orderRecordDaoConfig = daoConfigMap.get(OrderRecordDao.class).clone();
        orderRecordDaoConfig.initIdentityScope(type);

        baseNoticeDaoConfig = daoConfigMap.get(BaseNoticeDao.class).clone();
        baseNoticeDaoConfig.initIdentityScope(type);

        billRecordDaoConfig = daoConfigMap.get(BillRecordDao.class).clone();
        billRecordDaoConfig.initIdentityScope(type);

        personalInformationDao = new PersonalInformationDao(personalInformationDaoConfig, this);
        orderRecordDao = new OrderRecordDao(orderRecordDaoConfig, this);
        baseNoticeDao = new BaseNoticeDao(baseNoticeDaoConfig, this);
        billRecordDao = new BillRecordDao(billRecordDaoConfig, this);

        registerDao(PersonalInformation.class, personalInformationDao);
        registerDao(OrderRecord.class, orderRecordDao);
        registerDao(BaseNotice.class, baseNoticeDao);
        registerDao(BillRecord.class, billRecordDao);
    }
    
    public void clear() {
        personalInformationDaoConfig.getIdentityScope().clear();
        orderRecordDaoConfig.getIdentityScope().clear();
        baseNoticeDaoConfig.getIdentityScope().clear();
        billRecordDaoConfig.getIdentityScope().clear();
    }

    public PersonalInformationDao getPersonalInformationDao() {
        return personalInformationDao;
    }

    public OrderRecordDao getOrderRecordDao() {
        return orderRecordDao;
    }

    public BaseNoticeDao getBaseNoticeDao() {
        return baseNoticeDao;
    }

    public BillRecordDao getBillRecordDao() {
        return billRecordDao;
    }

}
